Repository Rosen-Team-B/Rosen_B, pull requests merged in 2022-11, with the labels that each got.

#15 Client Meeting Notes for W9
  documentation/meetings/clientMeetings/2022 11 01 - Client Meeting W9
Labels: chore

#16 Comp lib testing
  ComponentLibTesting/README.md
  ComponentLibTesting/test-app/package-lock.json
  ComponentLibTesting/test-app/package.json
  ComponentLibTesting/test-app/src/App.tsx
  ComponentLibTesting/test-app/src/Breadcrumb.tsx
  ComponentLibTesting/test-app/src/index.tsx
  mysite/db.sqlite3
  mysite/mysite/__pycache__/__init__.cpython-39.pyc
  mysite/mysite/__pycache__/settings.cpython-39.pyc
  mysite/mysite/__pycache__/urls.cpython-39.pyc
  mysite/mysite/__pycache__/wsgi.cpython-39.pyc
Labels: exploration

#25 Design refinement w9
  documentation/design ideas w9.md
Labels: exploration

#17 Renamed W4 notes and added W9 notes
  documentation/meetings/teamMeetings/2022 10 06 - Team meeting W4.md
  documentation/meetings/teamMeetings/2022 11 03 - Team Meeting W9.md
Labels: chore

#7 Docker fronted setup
  App/rosen_app/.dockerignore
  App/rosen_app/Dockerfile
  App/rosen_app/README.md
  App/rosen_app/docker-compose.yaml
Labels: task

#22 Button component template creation
  App/rosenFrontend/package-lock.json
  App/rosenFrontend/src/Components/submitButton.tsx
Labels: task

#37 Removing old BE Code
  mysite/db.sqlite3
  mysite/mysite/__pycache__/__init__.cpython-39.pyc
  mysite/mysite/__pycache__/settings.cpython-39.pyc
  mysite/mysite/__pycache__/urls.cpython-39.pyc
  mysite/mysite/__pycache__/wsgi.cpython-39.pyc
Labels: chore

#40 Add to readme frontend
  App/rosenFrontend/README.md
  App/rosenFrontend/package-lock.json
  App/rosenFrontend/package.json
Labels: chore

#42 add instructions
  App/rosenFrontend/README.md
Labels: chore

#51 Reorganization and page creation
  App/rosenFrontend/package-lock.json
  App/rosenFrontend/package.json
  App/rosenFrontend/src/App.js
  App/rosenFrontend/src/App.test.js
  App/rosenFrontend/src/components/App.tsx
  App/rosenFrontend/src/components/Step1.tsx
  App/rosenFrontend/src/components/Step2.tsx
  App/rosenFrontend/src/components/Step3.tsx
  App/rosenFrontend/src/components/Step4.tsx
  App/rosenFrontend/src/components/shared/button/submitButton.tsx
  App/rosenFrontend/src/index.js
  App/rosenFrontend/src/index.tsx
  App/rosenFrontend/src/logo.svg
  App/rosenFrontend/src/reportWebVitals.js
  App/rosenFrontend/src/setupTests.js
  App/rosenFrontend/src/styles/App.css
  App/rosenFrontend/src/styles/index.css
  App/rosenFrontend/tsconfig.json
Labels: task

#48 Uploading W11/W12 Client Meeting Notes
  documentation/meetings/clientMeetings/2022 11 15 - Client Meeting W11
Labels: chore

#52 Button routing
  App/rosenFrontend/src/components/App.tsx
  App/rosenFrontend/src/components/Step1.tsx
  App/rosenFrontend/src/components/Step2.tsx
  App/rosenFrontend/src/components/Step3.tsx
  App/rosenFrontend/src/components/Step4.tsx
  App/rosenFrontend/src/components/pages/Home.tsx
  App/rosenFrontend/src/components/pages/Stepper.tsx
  App/rosenFrontend/src/components/shared/button/submitButton.tsx
  App/rosenFrontend/src/constants/routes.ts
Labels: task

#53 Button function
  App/rosenFrontend/src/components/pages/Home.tsx
  App/rosenFrontend/src/components/shared/button/Button.tsx
  App/rosenFrontend/src/components/shared/button/Button.types.ts
  App/rosenFrontend/src/styles/Button.styles.css
Labels: task

#56 added styles
  App/rosenFrontend/src/components/step_instructions.JSON
  App/rosenFrontend/src/styles/sassstyles/body.scss
  App/rosenFrontend/src/styles/sassstyles/button_styles.scss
  App/rosenFrontend/src/styles/sassstyles/colors.scss
Labels: chore

#63 add upload button
  App/rosenFrontend/src/components/shared/uploadButton/UploadButton.tsx
Labels: task, P1

#59 Page header
  App/rosenFrontend/src/components/shared/pageHeader/PageHeader.module.scss
  App/rosenFrontend/src/components/shared/pageHeader/PageHeader.tsx
  App/rosenFrontend/src/components/shared/pageHeader/Rosen_logo.png
  App/rosenFrontend/src/react-env.d.ts
Labels: task, P1

#60 making the app pretty for the demo
  App/rosenFrontend/package-lock.json
  App/rosenFrontend/src/components/pages/ProgressiveStepper.tsx
  App/rosenFrontend/src/components/step_instructions.JSON
Labels: task

#64 Edit readme
  README.md
Labels: chore
