Repository Rosen-Team-B/Rosen_B, pull requests merged in 2022-12, with the labels that each got.

#66 Integrate frontend - demo purpose (only?)
  App/rosenFrontend/src/components/pages/Home.tsx
  App/rosenFrontend/src/components/pages/ProgressiveStepper.tsx
  App/rosenFrontend/src/components/shared/uploadButton/UploadButton.tsx
  App/rosenFrontend/src/styles/index.css
Labels: task

#74 installing packages
  ComponentLibTesting/test-app/package-lock.json
  ComponentLibTesting/test-app/package.json
Labels: exploration

#72 Integrating DjangoREST Framework into project
  App/rosen_backend/README.md
  App/rosen_backend/siteConfig/settings.py
  App/rosen_backend/siteConfig/urls.py
Labels: task

#71 Client Meeting Notes W13
  documentation/meetings/clientMeetings/2022 11 29 - Client Meeting W13.md
Labels: chore

#69 Create 2022 11 29 - Team Meeting W13.md
  documentation/meetings/teamMeetings/2022 11 29 - Team Meeting W13.md
Labels: chore

#82 Comp lib readme update
  App/rosenFrontend/README.md
Labels: chore

#76 Step 5 Img gallery test
  ComponentLibTesting/test-app/package-lock.json
  ComponentLibTesting/test-app/package.json
  ComponentLibTesting/test-app/src/Gallery.tsx
  ComponentLibTesting/test-app/src/ImgComponent.tsx
  ComponentLibTesting/test-app/src/assets/test-img.jpg
Labels: task
